---
title: "Project Draft workshop"
author: "Joseph G., Barbara S."
date: "2026-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(tidyr)
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(plotly)
library(priceR)            

my_data <- read.csv("imdb_top_1000.csv")
glimpse(my_data)

```
# Data Cleaning: emo::ji("smile")

```{r}
my_data$Released_Year <- as.numeric(my_data$Released_Year )
my_data$Gross <- as.numeric(my_data$Gross)
my_data$Runtime <-as.numeric(my_data$Runtime)
```


```{r}
# What are the top 5 directors with the the highest movie rating?

 top_5_directors <- my_data %>%  
   group_by(Director)%>%         
   summarise(avg_rating = mean(IMDB_Rating, na.rm = TRUE))%>% 
   arrange(desc(avg_rating))%>%  
   head(5)                     
 print(top_5_directors)         
p <- ggplot(top_5_directors, aes(x = Director, y = avg_rating, fill = Director)) + geom_col() + labs(title = "TOP 5 DIRECTORS BY AVERGAE RATING", x= "Director's name", y = "IMDB Average rating")       

```
1. What is the relationship between ratings and runtime?

```{r}

my_data <- my_data%>%
  mutate(Runtime = as.numeric(gsub(" min", "", Runtime)))
  
ggplot(my_data, aes(x = Runtime, y = IMDB_Rating)) +
  geom_point(alpha = 0.6) +
  labs(
    title = "People's Rating vs Runtime",
    x = "Runtime",
    y = "IMDb Rating"
  )
```



```{r}
ggplot(my_data, aes(x = Runtime, y = Meta_score)) +
  geom_point(alpha = 0.6) +
  labs(
    title = "Critics Score vs Runtime",
    x = "Runtime",
    y = "Meta_score"
  )
```
```{r}
# Who are the top 5 lead actors among the top imdp movies and how many times they appear in this data set ranking. 

library(dplyr)
top_actors <- my_data%>%
  group_by(Star1)%>%
  summarise(Movie_count = n())%>%
  arrange(desc(Movie_count))%>%
  head(10)
print(top_actors)

library(ggplot2)
g <- ggplot(top_actors, aes(x = Star1, y = Movie_count, fill = Star1)) + geom_col() +labs(title = "Top 5 lead actors and how many time they appear in the data set", x = "Lead actor's name", y = "Amount of times they appear in the dataset" )
library(plotly)
ggplotly(g)
```

2.	Which genres tend to have the longest runtime?

```{r}
my_data <- my_data %>%
  mutate(Runtime = as.numeric(gsub("[^0-9]", "", Runtime)))

my_data_genre <- my_data %>%
  separate_rows(Genre, sep = ", ")

genre_runtime <- my_data_genre %>%
  group_by(Genre) %>%
  summarize(avg_runtime = mean(Runtime, na.rm = TRUE)) %>%
  arrange(desc(avg_runtime))

head(genre_runtime)
```


```{r}
ggplot(genre_runtime, aes(x = reorder(Genre, avg_runtime), y = avg_runtime)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Average Runtime by Genre",
    x = "Genre",
    y = "Average Runtime (minutes)"
  )
```



```{r}
country <- "US"
inflation_dataframe <- retrieve_inflation_data(country)
countries_dataframe <- show_countries()

decade_gross <- my_data %>%
  mutate(adjusted_gross = adjust_for_inflation(parse_number(Gross), as.numeric(Released_Year), country, to_date = 2024), 
         Decade = (as.numeric(Released_Year) %/% 10) * 10) %>%
  filter(!is.na(Decade), !is.na(Gross)) %>%
  group_by(Decade)
# 
# %>%
#   summarize(
#     Average_Gross = mean(Gross, na.rm = TRUE),
#     Average_adjusted_gross = mean(adjusted_gross, na.rm = TRUE),
#     Movie_Count = n(),
#     .groups = "drop"
#   ) 

decade_gross$Gross
decade_gross$adjusted_gross

ggplot(decade_gross, aes(x = Decade, y = Average_Gross)) + geom_line()+geom_point()
ggplotly(l)
```
 


3. Which genre produces the most highly-rated movies (rating > 8.5)?

```{r}
high_rated <- my_data %>%
  filter(IMDB_Rating > 8.5)

high_rated_genre <- high_rated %>%
  separate_rows(Genre, sep = ", ")

genre_counts <- high_rated_genre %>%
  group_by(Genre) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

head(genre_counts)
```

```{r}
ggplot(genre_counts, aes(x = reorder(Genre, count), y = count)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Number of Highly Rated Movies (IMDb > 8.5) by Genre",
    x = "Genre",
    y = "Count of Movies"
  )
```

```{r}

```

